// <auto-generated />
using System;
using AppWebSite.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppWebSite.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20200110022148_MigrationDB")]
    partial class MigrationDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AppWebSite.Models.Encuesta", b =>
                {
                    b.Property<DateTime>("Enfecha")
                        .HasColumnName("enfecha")
                        .HasColumnType("date");

                    b.Property<string>("Enemail")
                        .HasColumnName("enemail")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<int>("Encalificacion")
                        .HasColumnName("encalificacion");

                    b.Property<string>("Ennombre")
                        .IsRequired()
                        .HasColumnName("ennombre")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.HasKey("Enfecha", "Enemail");

                    b.ToTable("encuesta");
                });
#pragma warning restore 612, 618
        }
    }
}
